modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="invisibilityhat"
version="${file.jarVersion}"
displayName="Invisibility Hat"
logoFile="icon.png"
credits=""
authors="Bradlee Barnes"
description='''
Allows the player to go invisible, but with an interesting side effect.
View full description on Modrinth/GitHub!
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"