modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="invisibilityhat"
version="1.0.0"
displayName="Invisibility Hat"
logoFile="icon.png"
credits=""
authors="Bradlee Barnes"
description='''
Allows the player to go invisible, but with an interesting side effect.
View full description here: https://github.com/StupidRepo/InvisibilityHat
'''

[[dependencies.invisibilityhat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invisibilityhat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"